name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: erlef/setup-beam@v1.9.0
        with:
          otp-version: 24.0
          elixir-version: 1.12.2
      - run: mix test
      - run: mix format --check-formatted
